#Dummy edit to change last committer
language: node_js
env: DISPLAY=:99.0
node_js:
  - 0.10

before_script:
  - "./node_modules/bower/bin/bower install"
  - "sh -e /etc/init.d/xvfb start"
  - npm start &
  - sleep 5
